export const GET_HISTORY = 'GET_HISTORY'
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS'
export const GET_SESSION_LIST = 'GET_SESSION_LIST'
export const GET_SESSION_LIST_SUCCESS = 'GET_SESSION_LIST_SUCCESS'
